#### general settings
name: MGTV_EDVR
use_tb_logger: true
model: video_base
distortion: sr
scale: 1
gpu_ids: [0,1,2,3]

#### datasets
datasets:
  train:
    name: MGTV
    mode: MGTV
    interval_list: [1]
    random_reverse: false
    border_mode: true
    dataroot_GT: /data/yangxi/MGTV/GT_frames
    dataroot_LQ: /data/yangxi/MGTV/LQ_frames
    cache_keys: ../keys/all_keys.pkl
    outlier_seqs: ~
    train_seqs: ../keys/train_seqs.pkl
    valid_seqs: ../keys/valid_seqs.pkl
    scene_index: ../keys/scene_index.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 8
    crop_h: 384
    crop_w: 384
    use_flip: true
    use_rot: true

  val:
    name: MGTV
    mode: MGTV
    interval_list: [1]
    random_reverse: false
    border_mode: true
    dataroot_GT: /data/yangxi/MGTV/GT_frames
    dataroot_LQ: /data/yangxi/MGTV/LQ_frames
    cache_keys: ../keys/all_keys.pkl
    outlier_seqs: ~
    train_seqs: ../keys/train_seqs.pkl
    valid_seqs: ../keys/valid_seqs.pkl
    scene_index: ../keys/scene_index.pkl

    N_frames: 7
    use_shuffle: false
    n_workers: 3  # per GPU
    batch_size: 1
    crop_h: 384
    crop_w: 384
    use_flip: false
    use_rot: false


#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: true
  w_TSA: true

#### path
path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
